"""
Helpers for preparing data consumed by the Chart Explorer UI.

The explorer combines historical fundamentals, price series, and the technical
Plotly figure generated by the Epic 3 analyzer.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Mapping, Optional, Sequence

from bd_stockevaluator.core.service import StockAnalysisService

_EMPTY_FIGURE = {"data": [], "layout": {"title": "Technical chart unavailable"}}


def _normalise_history(
    entries: Optional[Sequence[Mapping[str, Any]]],
) -> List[Dict[str, Any]]:
    if not entries:
        return []
    normalised: List[Dict[str, Any]] = []
    for entry in entries:
        record: Dict[str, Any] = {}
        for key, value in entry.items():
            if isinstance(value, datetime):
                record[key] = value.isoformat()
            else:
                record[key] = value
        normalised.append(record)
    return normalised


def _resolve_chart_path(
    path_str: Optional[str], root: Optional[Path]
) -> Optional[Path]:
    if not path_str:
        return None
    candidate = Path(path_str)
    if candidate.is_file():
        return candidate
    if root:
        if not candidate.is_absolute():
            relative_candidate = root / candidate
            if relative_candidate.is_file():
                return relative_candidate
        # Handle cases where the stored path already contains "static/"
        filename = Path(path_str).name
        candidate = root / filename
        if candidate.is_file():
            return candidate
        charts_dir = root / "charts" / filename
        if charts_dir.is_file():
            return charts_dir
    return None


def _load_chart_json(path_str: Optional[str], root: Optional[Path]) -> Dict[str, Any]:
    resolved = _resolve_chart_path(path_str, root)
    if resolved and resolved.is_file():
        try:
            return json.loads(resolved.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return dict(_EMPTY_FIGURE)
    return dict(_EMPTY_FIGURE)


@dataclass(frozen=True)
class ChartExplorerPayload:
    ticker: str
    company_name: str
    fundamentals_history: List[Dict[str, Any]]
    price_history: List[Dict[str, Any]]
    technical_figure_json: Dict[str, Any]


def collect_chart_explorer_payload(
    ticker: str,
    service: StockAnalysisService,
    *,
    chart_json_root: Optional[Path] = None,
) -> ChartExplorerPayload:
    analysis = service.analyze(ticker, include_opinion=False)
    fundamentals_history = _normalise_history(analysis.get("fundamentals_history"))
    price_history = _normalise_history(analysis.get("price_history"))
    technical_chart = analysis.get("technical_analysis", {}).get("chart", {})
    technical_figure_json = _load_chart_json(
        technical_chart.get("json"),
        chart_json_root,
    )

    return ChartExplorerPayload(
        ticker=analysis.get("ticker", ticker),
        company_name=analysis.get("company_name", ticker),
        fundamentals_history=fundamentals_history,
        price_history=price_history,
        technical_figure_json=technical_figure_json,
    )


__all__ = ["ChartExplorerPayload", "collect_chart_explorer_payload"]
